#!/usr/bin/env python3
"""Decide whether to open a new link-check issue for one site, and if so,
render its body.

Reads:  lychee-report.json, open-issues.json, $SITE_NAME, $SITE_URL
Writes: issue-body.md and changed=/title=/total= to $GITHUB_OUTPUT
"""

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
REPORT_FILE = ROOT / "lychee-report.json"
OPEN_ISSUES_FILE = ROOT / "open-issues.json"
ISSUE_BODY_FILE = ROOT / "issue-body.md"

PAGE_HEADER_RE = re.compile(r"^###\s+\[(https?://[^\]]+)\]")
BROKEN_LINK_RE = re.compile(r"^-\s+`(https?://[^`]+)`")

SITEMAP_SUFFIXES = ("sitemap.xml", "sitemap-index.xml", "sitemap_index.xml")


def site_prefix(url):
    """Strip a trailing sitemap filename to get the canonical site URL."""
    for suffix in SITEMAP_SUFFIXES:
        if url.endswith(suffix):
            return url[: -len(suffix)]
    return url


def load_json(path, default):
    if not path.exists():
        return default
    text = path.read_text().strip()
    if not text:
        return default
    return json.loads(text)


def parse_lychee_report(report):
    """Extract {(source_page, broken_url): status_text} from a lychee report."""
    pairs = {}
    fail_map = report.get("fail_map") or report.get("error_map") or {}
    for source, entries in fail_map.items():
        for entry in entries:
            url = entry.get("url")
            if not url:
                continue
            status = entry.get("status") or {}
            text = status.get("text") or status.get("code") or "Unknown"
            pairs[(source, url)] = str(text)
    return pairs


def extract_reported_pairs(open_issues):
    """Return the set of (page, url) pairs already covered by open issues."""
    reported = set()
    for issue in open_issues:
        body = issue.get("body") or ""
        current_page = None
        for line in body.splitlines():
            page = PAGE_HEADER_RE.match(line)
            if page:
                current_page = page.group(1)
                continue
            link = BROKEN_LINK_RE.match(line)
            if link and current_page:
                reported.add((current_page, link.group(1)))
    return reported


def render_issue_body(site_name, site_url, pairs):
    canonical = site_prefix(site_url)
    total = len(pairs)
    lines = [
        f"Automated link check found **{total} newly broken link"
        f"{'s' if total != 1 else ''}** in [{site_name}]({canonical}). "
        f"Links already tracked in other open `link-check` issues for this "
        f"site are excluded from this report.",
        "",
        "Generated by `.github/workflows/docs-link-check.yaml`.",
        "",
    ]
    by_page = {}
    for (page, url), status in pairs.items():
        by_page.setdefault(page, {})[url] = status
    for page in sorted(by_page):
        urls = by_page[page]
        lines.append(f"### [{page}]({page})")
        lines.append("")
        for url in sorted(urls):
            lines.append(f"- `{url}`: {urls[url]}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_output(name, value):
    output = os.environ.get("GITHUB_OUTPUT")
    if not output:
        print(f"{name}={value}", file=sys.stderr)
        return
    with open(output, "a") as f:
        f.write(f"{name}={value}\n")


def main():
    site_name = os.environ.get("SITE_NAME")
    site_url = os.environ.get("SITE_URL")
    if not site_name or not site_url:
        print("SITE_NAME and SITE_URL env vars are required", file=sys.stderr)
        sys.exit(1)

    if not REPORT_FILE.exists():
        print(f"Report file {REPORT_FILE} not found", file=sys.stderr)
        sys.exit(1)

    report = load_json(REPORT_FILE, {})
    current = parse_lychee_report(report)

    open_issues = load_json(OPEN_ISSUES_FILE, [])
    already_reported = extract_reported_pairs(open_issues)

    new_pairs = {
        pair: status
        for pair, status in current.items()
        if pair not in already_reported
    }

    if not new_pairs:
        print(
            f"{site_name}: {len(current)} broken link(s) found, all already "
            f"tracked in open issues. No new issue."
        )
        write_output("changed", "false")
        return

    body = render_issue_body(site_name, site_url, new_pairs)
    ISSUE_BODY_FILE.write_text(body)

    total = len(new_pairs)
    title = f"{site_name}: {total} broken link{'s' if total != 1 else ''}"
    write_output("changed", "true")
    write_output("title", title)
    write_output("total", str(total))
    print(f"{site_name}: {total} newly broken link(s).")


if __name__ == "__main__":
    main()
